// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <Arduino.h>
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "fd6ef8a6-ca44-4910-9629-aa1a43a04c28";

const char SSID[]               = "MURILO";//SECRET_SSID;    // Network SSID (name)
const char PASS[]               = "94658243";//SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "VSWNIVYFOGSYQBUSV1XS";//SECRET_DEVICE_KEY;    // Secret device password

void onSwitchChange();

CloudSwitch _switch_;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(_switch_, READWRITE, ON_CHANGE, onSwitchChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);